model_name: BiGRU_attention
embedding_dim: 32
gru_units: 16
dropout_rate: 0.2
attention_units: 32
output_size: 1
output_activation: sigmoid
learning_rate: 0.0001
loss: binary_crossentropy
metrics: [accuracy]
batch_size: 32
epochs: 10
validation_split: 0.2
